import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const AUTH_FETCH_INTERCEPTOR = `
(() => {
  const AUTH_HEADER = 'x-auth-token';
  const TOKEN_KEY = 'authToken';
  const FLAG = '__authFetchInterceptorInstalled';

  if (typeof window === 'undefined') {
    return;
  }

  if (window[FLAG]) {
    return;
  }

  window[FLAG] = true;

  const originalFetch = window.fetch.bind(window);

  window.fetch = function(input, init) {
    try {
      const request = new Request(input, init);
      let requestUrl;

      try {
        requestUrl = new URL(request.url, window.location.origin);
      } catch (_error) {
        requestUrl = null;
      }

      if (!requestUrl || requestUrl.origin !== window.location.origin) {
        return originalFetch(input, init);
      }

      const headers = new Headers(request.headers);
      const token = localStorage.getItem(TOKEN_KEY);

      if (token && token !== 'undefined' && token !== 'null' && token.trim() !== '') {
        headers.set(AUTH_HEADER, token);
      } else {
        headers.delete(AUTH_HEADER);
      }

      const modifiedRequest = new Request(request, { headers, signal: request.signal });

      return originalFetch(modifiedRequest);
    } catch (_error) {
      return originalFetch(input, init);
    }
  };
})();
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="auth-fetch-interceptor" strategy="beforeInteractive">
          {AUTH_FETCH_INTERCEPTOR}
        </Script>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
